apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis01
    #labels:
    #type: local
spec:
  #storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/redis01"
    type: DirectoryOrCreate
