apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis06
    #labels:
    #type: local
spec:
  #storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/redis06"
    type: DirectoryOrCreate
