apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
    #namespace: development
spec:
  #storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
