apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cluster
  labels:
    app: redis-cluster
spec:
  replicas: 6
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
      containers:
      - name: redis
        image: redis:5.0.1-alpine
        volumeMounts:
          - name: data
            mountPath: /data
        command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
        ports:
        - name: client
          containerPort: 6379
        - name: gossip
          containerPort: 16379
